export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_CHECK = "LOGIN_CHECK";
export const LOG_OUT = "LOG_OUT";

//Leads
export const LEAD_FETCH = "LEAD_FETCH";
export const LEAD_FETCH_SUCCESS = "LEAD_FETCH_SUCCESS";
export const LEAD_FETCH_FAILED = "LEAD_FETCH_FAILED";

export const LEAD_LOAD_CREATE = "LEAD_LOAD_CREATE";
export const LEAD_LOAD_CREATE_SUCCESS = "LEAD_LOAD_CREATE_SUCCESS";
export const LEAD_LOAD_CREATE_FAILED = "LEAD_LOAD_CREATE_FAILED";

export const LEAD_CREATE = "LEAD_CREATE";
export const LEAD_CREATE_INIT = "LEAD_CREATE_INIT";
export const LEAD_CREATE_SUCCESS = "LEAD_CREATE_SUCCESS";
export const LEAD_CREATE_FAILED = "LEAD_CREATE_FAILED";

export const LEAD_LOAD_UPDATE = "LEAD_LOAD_UPDATE";
export const LEAD_LOAD_UPDATE_SUCCESS = "LEAD_LOAD_UPDATE_SUCCESS";
export const LEAD_LOAD_UPDATE_FAILED = "LEAD_LOAD_UPDATE_FAILED";

export const LEAD_UPDATE = "LEAD_UPDATE";
export const LEAD_UPDATE_INIT = "LEAD_UPDATE_INIT";
export const LEAD_UPDATE_SUCCESS = "LEAD_UPDATE_SUCCESS";
export const LEAD_UPDATE_FAILED = "LEAD_UPDATE_FAILED";

export const LEAD_DELETE = "LEAD_DELETE";
export const LEAD_DELETE_INIT = "LEAD_DELETE_INIT";
export const LEAD_DELETE_SUCCESS = "LEAD_DELETE_SUCCESS";
export const LEAD_DELETE_FAILED = "LEAD_DELETE_FAILED";

export const REGION_FETCH = "REGION_FETCH";
export const REGION_FETCH_SUCCESS = "REGION_FETCH_SUCCESS";
export const REGION_FETCH_FAILED = "REGION_FETCH_FAILED";

export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_FETCH_SUCCESS= "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED";

export const LEAD_DETAIL_FETCH = "LEAD_DETAIL_FETCH";
export const LEAD_DETAIL_FETCH_SUCCESS = "LEAD_DETAIL_FETCH_SUCCESS";
export const LEAD_DETAIL_FETCH_FAILED = "LEAD_DETAIL_FETCH_FAILED";

//Home
export const RECENT_STATUS_LEADS_FETCH = "RECENT_STATUS_LEADS_FETCH";
export const RECENT_STATUS_LEADS_FETCH_SUCCESS = "RECENT_STATUS_LEADS_FETCH_SUCCESS";
export const RECENT_STATUS_LEADS_FETCH_FAILED = "RECENT_STATUS_LEADS_FETCH_FAILED";

export const RECENT_LEADS_FETCH = "RECENT_LEADS_FETCH";
export const RECENT_LEADS_FETCH_SUCCESS = "RECENT_LEADS_FETCH_SUCCESS";
export const RECENT_LEADS_FETCH_FAILED = "RECENT_LEADS_FETCH_FAILED";

export const LATEST_STATUS_FETCH = "LATEST_STATUS_FETCH";
export const LATEST_STATUS_FETCH_SUCCESS = "LATEST_STATUS_FETCH_SUCCESS";
export const LATEST_STATUS_FETCH_FAILED = "LATEST_STATUS_FETCH_FAILED";