export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_CHECK = "LOGIN_CHECK";
export const LOG_OUT = "LOG_OUT";

//Leads
export const LEAD_FETCH = "LEAD_FETCH";
export const LEAD_FETCH_SUCCESS = "LEAD_FETCH_SUCCESS";
export const LEAD_FETCH_FAILED = "LEAD_FETCH_FAILED";

export const REGION_FETCH = "REGION_FETCH";
export const REGION_FETCH_SUCCESS = "REGION_FETCH_SUCCESS";
export const REGION_FETCH_FAILED = "REGION_FETCH_FAILED";

export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_FETCH_SUCCESS= "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED";

export const LEAD_DETAIL_FETCH = "LEAD_DETAIL_FETCH";
export const LEAD_DETAIL_FETCH_SUCCESS = "LEAD_DETAIL_FETCH_SUCCESS";
export const LEAD_DETAIL_FETCH_FAILED = "LEAD_DETAIL_FETCH_FAILED";