export const LOCAL_LEADS_LIST = "LOCAL_LEADS_LIST";
export const LOCAL_REGIONS_LIST = "LOCAL_REGIONS_LIST";
export const LOCAL_PRODUCTS_LIST = "LOCAL_PRODUCTS_LIST";
export const LOCAL_TIPSTER_LIST = "LOCAL_TIPSTER_LIST";

//Mail
export const LOCAL_MESSAGE_LIST = "LOCAL_MESSAGE_LIST";
export const LOCAL_HOME = "LOCAL_HOME";

//User
export const LOCAL_USER_INFO = "LOCAL_USER_INFO";